### ISSUE TITLE
java.io.FileNotFoundException on missing config.yml

### ISSUE THREAD

**Issue by Kogarou-san** [PTOM76/EnhancedQuarries#17]
There is an unhandled FileNotFoundException when attempting to load a non-existent config.yml, in version 1.2.0 for Minecraft  1.17.1 . I have not tested in older/newer Minecraft versions, but the same bug is likely present in other versions too.

[19:52:38] [Render thread/INFO]: Common init
[19:52:38] [Render thread/INFO]: [Enhanced Quarries] Initializing
java.io.FileNotFoundException: A:\MultiMC\instances\1.17.1-mod\.minecraft\config\enhanced_quarries\config.yml (The system cannot find the path specified)
	at java.base/java.io.FileInputStream.open(Unknown Source)
	at java.base/java.io.FileInputStream.<init>(Unknown Source)
	at ml.pkom.enhancedquarries.easyapi.FileControll.fileReadContents(Unknown Source)
	at ml.pkom.enhancedquarries.easyapi.config.YamlConfig.load(Unknown Source)
	at ml.pkom.enhancedquarries.easyapi.config.Config.<init>(Unknown Source)
	at ml.pkom.enhancedquarries.easyapi.config.YamlConfig.<init>(Unknown Source)
	at ml.pkom.enhancedquarries.Configs.<clinit>(Unknown Source)
	at ml.pkom.enhancedquarries.EnhancedQuarries.onInitialize(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2960/0x0000000000000000.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(Unknown Source)
	at net.minecraft.class_310.redirect$zim000$catchFabricInit(Unknown Source)
	at net.minecraft.class_310.<init>(Unknown Source)
	at net.minecraft.client.main.Main.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(Unknown Source)
	at net.fabricmc.loader.launch.knot.Knot.launch(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClient.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launch(Unknown Source)
	at org.multimc.EntryPoint.listen(Unknown Source)
	at org.multimc.EntryPoint.main(Unknown Source)
Process crashed with exitcode -1073740791.

**Comment by PTOM76** [comment]
We couldn't reproduce this issue.
Is it 1.2.0RC5?

**Comment by PTOM76** [comment]
I couldn't reproduce this issue.
Is it 1.2.0RC5?
